logicProject/logicProject/Models/ViewModel/ItemSuppliedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using logicProject.Models.EF;

namespace logicProject.Models.ViewModel
{
    //Coded by Antonio
    public class ItemSuppliedViewModel
    {
        public Product product { get; set; }
        public Supplier supplier { get; set; }
        public SupplierProduct supplierproduct { get; set; }
    }
}

logicProject/logicProject/Controllers/ManagerController.cs
using logicProject.Models.DBContext;
using logicProject.Models.EF;
using logicProject.Models.ViewModel;
using logicProject.Utility;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace logicProject.Controllers
{
    public class ManagerController : Controller 
    {
        private LogicEntities db = new LogicEntities();
        // GET: Manager
        public ActionResult Index()
        {
            return View();
        }
        //Code written by Antonio for the manager begins below
        public ActionResult ProductCategory()
        {
            var categories = db.Product.Select(p => p.Category).Distinct().ToList();
            ViewData["category"] = categories;
            return View();
        }

        public ActionResult ProductDetails(string category)
        {
            List<Product> products = db.Product.Where(pro => pro.Category == category).ToList();
            ViewData["productdetails"] = products;
            ViewData["category"] = category;
            return View();
        }
        public ActionResult StockCardDetails(string id, string startDate, string endDate)
        {
            Product product = db.Product.Find(id);

            List<SupplierProduct> supplierproduct = db.SupplierProduct.OrderBy(pro => pro.Price).Where(pro => pro.ProductId == id).ToList();
            ViewData["supplierproduct"] = supplierproduct;

            if (startDate != null && endDate != null)
            {
                DateTime start = DateTime.Parse(startDate);
                DateTime end = DateTime.Parse(endDate);
                List<StockTransaction> stockCardDetails = db.StockTransaction.Where(p => p.ProductId == id && p.TranDate > start && p.TranDate < end).ToList();
                ViewData["stockcarddetails"] = stockCardDetails;
            }
            else
            {
                List<StockTransaction> stockCardDetails = db.StockTransaction.Where(p => p.ProductId == id).ToList();
                ViewData["stockcarddetails"] = stockCardDetails;
            }

            return View(product);
        }
        //public ActionResult CreateProduct()
        //{

        //    return View();
        //}

        //// POST: Products/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult CreateProduct([Bind(Include = "ProductId,Category,Description,Bin,Unit,Qty,ReorderLevel,ReorderQty")] Product product)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Product.Add(product);
        //        db.SaveChanges();
        //        return RedirectToAction("ProductDetails", new { category = product.Category });
        //    }
        //    return View(product);
        //}


        //// GET: Products/Edit/5
        //public ActionResult EditProduct(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Product product = db.Product.Find(id);
        //    if (product == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(product);
        //}

        //// POST: Products/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditProduct([Bind(Include = "ProductId,Category,Description,Bin,Unit,Qty,ReorderLevel,ReorderQty")] Product product)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(product).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("ProductDetails", new { category = product.Category });
        //    }
        //    return View(product);
        //}

        //// GET: Products/Delete/5
        //public ActionResult DeleteProduct(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Product product = db.Product.Find(id);

        //    if (product == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(product);
        //}

        //// POST: Products/Delete/5
        //[HttpPost, ActionName("DeleteProduct")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmedProduct(string id)
        //{
        //    Product product = db.Product.Find(id);
        //    db.Product.Remove(product);
        //    db.SaveChanges();
        //    return RedirectToAction("ProductDetails", new { category = product.Category });
        //}

        public ActionResult SupplierList()
        {
            return View(db.Supplier.ToList());
        }

        // GET: Suppliers/Create
        public ActionResult CreateSupplier()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSupplier([Bind(Include = "SupplierId,SupplierName,GSTRegNo,ContactName,FaxNo,PhNo,Address")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Supplier.Add(supplier);
                db.SaveChanges();
                return RedirectToAction("SupplierList");
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public ActionResult EditSupplier(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Supplier.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSupplier([Bind(Include = "SupplierId,SupplierName,GSTRegNo,ContactName,FaxNo,PhNo,Address")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SupplierList");
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public ActionResult DeleteSupplier(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Supplier.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("DeleteSupplier")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedSupplier(string id)
        {
            Supplier supplier = db.Supplier.Find(id);
            db.Supplier.Remove(supplier);
            db.SaveChanges();
            return RedirectToAction("SupplierList");
        }
        public ActionResult ItemSupplied(string supplierid)
        {
            //SELECT s.ProductId,p.Category,p.[Description],s.Price
            //FROM SupplierProducts s, Suppliers sp,Products p
            //WHERE s.SupplierId = 'ALPA' AND p.ProductId = s.ProductId AND s.SupplierId = sp.SupplierId;

            SupplierProduct suppro = db.SupplierProduct.Where(pro => pro.SupplierId == supplierid).First();

            List<Product> products = db.Product.ToList();
            List<Supplier> suppliers = db.Supplier.ToList();
            List<SupplierProduct> supplierproducts = db.SupplierProduct.Where(sup => sup.SupplierId == supplierid).ToList();

            if (suppro == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewData["supplierproducts"] = suppro;
            }

            List<ItemSuppliedViewModel> data = (from sp in supplierproducts
                                                join s in suppliers on sp.SupplierId equals s.SupplierId
                                                join p in products on sp.ProductId equals p.ProductId
                                                select new ItemSuppliedViewModel { product = p, supplier = s, supplierproduct = sp }).ToList();

            return View(data);
        }
        public ActionResult CreateItemSupplied(string supplierId)
        {
            Supplier supplier = db.Supplier.Where(x => x.SupplierId == supplierId).SingleOrDefault();
            ViewData["supplier"] = supplier;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItemSupplied([Bind(Include = "SupplierProductId,ProductId,SupplierId,Price")]SupplierProduct supplierProduct)
        {
            if (ModelState.IsValid)
            {
                db.SupplierProduct.Add(supplierProduct);
                db.SaveChanges();

logicProject/logicProject/Views/Manager/ApproveForm.cshtml
@using logicProject.Models.EF;
@model logicProject.Models.EF.AdjustmentDetail


@{
    ViewBag.Title = "ApproveForm";
    //Written by Udaya
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    List<AdjustmentDetail> cart_list = (List<AdjustmentDetail>)ViewData["cart_list"];
    StoreStaff user = (StoreStaff)Session["StoreStaff"];
    Adjustment reqId = ViewData["adjustment"] as Adjustment;
}

<h2>Approve Inventory Adjustment Status</h2>
<br />

@using (Html.BeginForm("ApproveForm", "Manager", FormMethod.Post))
{
    <div class="box">
        <div id="table1">

            <table style="border: 1px solid black">
                <thead>
                    <tr>
                        <td>
                            <strong>Product code</strong>
                        </td>
                        <td>
                            <strong>Qty</strong>
                        </td>
                        <td>
                            <strong>Unit price</strong>
                        </td>
                        <td>
                            <strong>Total price</strong>
                        </td>
                        <td>
                            <strong>Reason</strong>
                        </td>
                    </tr>
                </thead>


                @foreach (var item in cart_list)
                {
                    <tr>
                        <td>
                            @item.ProductId
                        </td>
                        <td>
                            @item.Qty
                        </td>
                        <td>
                            @item.UnitPrice
                        </td>
                        <td>
                            @item.TotalPrice
                        </td>
                        <td>
                            @item.reason
                        </td>
                    </tr>
                }


            </table>
        </div>

        <br />
        <br />

        @{ if (reqId.Status.Equals("Pending"))
            {
                <input type="hidden" name="id" value="@reqId.AdjustmentId" />
                <p><strong>Remarks:</strong>@Html.TextArea("remarks", null, new { @class = "form-control", rows = "4", cols = "50" })</p>
                <br />
                <input type="submit" name="approve" value="Approve" class="btn btn btn-bitbucket" />
                <input type="submit" name="reject" value="Reject" class="btn btn-pinterest" />
            }

        }

    </div>

    <style>
        table {
            border: 1px solid black;
            width: 100%;
        }

        tr, td {
            padding: 10px;
            border: 1px solid black;
            text-align: center;
        }
    </style>
}

logicProject/logicProject/Views/Manager/Chart.cshtml
@{
    /**/

    ViewBag.Title = "dummy";
    var list1 = ViewBag.MONS;
    var list2 = ViewBag.QTYS;
    Dictionary<string, string> dict_ = ViewBag.dict;
    string month = (string)ViewBag.monthid;
    string itemselectedid = (string)ViewBag.itemid;
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    //Written by Udaya
    Dictionary<string, string> dict = new Dictionary<string, string>() { { "Select Category", "0" }, { "Clip", "1" }, { "Envelope", "2" }, { "Eraser", "3" }, { "Exercise", "4" }, { "File", "5" }, { "Pen", "6" }, { "Puncher", "7" },
                   { "Pad", "8" }, { "Paper", "9" }, { "Ruler", "10" }, { "Scissors", "11" }, { "Tape", "12" }, { "Sharpener", "13" }, { "ShortHand", "14" }, { "Stapler", "15" }, { "Tacks", "16" }, { "Tparency", "17" }, { "tray", "18" }};
    Dictionary<string, string> mon = new Dictionary<string, string>() { { "Select Month", "0" }, { "jan", "1" }, { "feb", "2" }, { "mar", "3" }, { "apr", "4" }, { "may", "5" }, { "jun", "6" }, { "jul", "7" }, { "aug", "8" }, { "sep", "9" }, { "oct", "10" }, { "nov", "11" }, { "dec", "12" } };
    string monthselected = mon.Where(x => x.Value == month).Select(x => x.Key).First() == null ? "mar" : mon.Where(x => x.Value == month).Select(x => x.Key).First();
    string itemselected = dict.Where(x => x.Value == itemselectedid).Select(x => x.Key).First() == null ? "Clip" : dict.Where(x => x.Value == itemselectedid).Select(x => x.Key).First();
}
<head>
    <script src="~/Scripts/Chart.min.js"></script>


    <style>
        #chart_container {
            width: 400px;
            height: 400px;
            border: 1px solid #ddd;
            padding: 1px;
            border-radius: 4px;
            float: left;
            clear: left;
        }
        #report {
            float: left;
            clear: right;
            padding-left: 30px;
        }
    </style>
</head>
<script>
    function onChange() {
        var e = document.getElementById("itemId");
        console.log(e.options[e.selectedIndex].value);
        var etochange = document.getElementById("ITEMID");
        etochange.value = e.options[e.selectedIndex].value;
    };
    function onChange_() {
        var e = document.getElementById("monId");
        console.log(e.options[e.selectedIndex].value);

        var etochange = document.getElementById("MONID");
        etochange.value = e.options[e.selectedIndex].value;

    };
</script>

<h2>Stationery Trend Analysis and Prediction</h2>

@using (Html.BeginForm("GenChart", "Manager", FormMethod.Post))
{

    <div id="generate_chart">
        <table>

            <tr>

                <td>
                    <strong>Item:    </strong>
                    @Html.DropDownList("Select Item", dict.Select(item => new SelectListItem { Text = item.Key, Value = item.Value }), new { id = "itemId", onchange = "onChange()", required = true })
                </td>

                <td>
                    <strong>Month:    </strong>
                    @Html.DropDownList("Select Item", mon.Select(item => new SelectListItem { Text = item.Key, Value = item.Value }), new { id = "monId", onchange = "onChange_()", required = true })

                </td>

                <td>
                    <input type="hidden" value="1" name="ITEMID" id="ITEMID" />
                    <input type="hidden" value="1" name="MONID" id="MONID" />
                    <input type="submit" value="Generate chart" />
                </td>
            </tr>

        </table>

    </div>

}
<div id="chart_container">
    <canvas id="bar_chart"></canvas>

</div>

<br />


@if (ViewBag.status)
{
<div id="report">
    <div>
        <strong>Predicted Category :</strong> @itemselected
    </div>
    <div>
        <strong>Predicted month :</strong> @monthselected
    </div>
    <div>
        <strong>Projected demand for @monthselected : </strong>@dict_[@monthselected]
    </div>
</div>
    
}


<script>

        var monthArray = @Html.Raw(Json.Encode(@dict_.Keys));
        var qtys = @Html.Raw(Json.Encode(dict_.Values));


        var ctx = $("#bar_chart");
        var barChart = new Chart(ctx, {

            type: 'bar',
            data: {
                labels: monthArray,
                datasets: [{
                    label: "Stationery Bar Chart",
                    data: qtys,
                    backgroundColor: ["rgba(242,166,54,.5)", "rgba(145,65,72,.5)", "rgba(74,25,92,.5)"],
                    borderColor: ["rgb(242,166,54)", "rgb(145,65,72)", "rgb(74,25,92)"],
                    borderWidth: 1

                }]
            },

            options: {

                maintainAspectRatio: false,
                scales: { xAxes: [{ ticks: { beginAtZero: true } }], yAxes: [{ ticks: { beginAtZero: true }}] },
                legend: {display:false}
            },

        });

</script>



<style>

    table {
        border-collapse: collapse;
    }

    .gfg {
        border-collapse: separate;
        border-spacing: 0 15px;
    }

    th, td {
        width: 220px;
        text-align: center;
        padding: 5px
    }

    #generate_chart {
        padding-bottom: 25px;
    }
</style>

logicProject/logicProject/Views/Manager/CreateItemSupplied.cshtml
@model logicProject.Models.EF.SupplierProduct
@using logicProject.Models.EF

@{
    ViewBag.Title = "CreateItemSupplied";
    Supplier supplier = (Supplier)ViewData["supplier"];
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    //Written By Antonio
}

<h2>Create Item Supplied</h2>
<p>SUPPLIER CODE : @supplier.SupplierId</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => supplier.SupplierId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back To List", "ItemSupplied", new { supplierId = supplier.SupplierId })
</div>

logicProject/logicProject/Views/Manager/CreateSupplier.cshtml
@model logicProject.Models.EF.Supplier

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    //Written By Antonio
}

<h2>ADD NEW / EDIT SUPPLIER</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SupplierId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SupplierId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SupplierId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SupplierName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SupplierName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSTRegNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GSTRegNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GSTRegNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FaxNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FaxNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "SupplierList")
</div>

logicProject/logicProject/Views/Manager/DeleteItemSupplied.cshtml
@model logicProject.Models.EF.SupplierProduct
@using logicProject.Models.EF

@{
    ViewBag.Title = "DeleteItemSupplied";
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    //Written by Antonio
}

<h2>Delete Item Supplied</h2>

<h2>Are you sure you want to delete this?</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => @model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => @model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.SupplierProductId)
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.SupplierId)
        @Html.HiddenFor(model => model.Price)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "SupplierList")
        </div>
    }
</div>

logicProject/logicProject/Views/Manager/StockCardDetails.cshtml
@model logicProject.Models.EF.Product
@using logicProject.Models.EF

@{
    ViewBag.Title = "StockCardDetails";
    var supplierproduct = (List<SupplierProduct>)ViewData["supplierproduct"];
    var stockcarddetails = (List<StockTransaction>)ViewData["stockcarddetails"];
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    //Written By Antonio
}

<h2>Stock Card Details</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.ProductId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ProductId)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Bin)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Bin)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Unit)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Unit)
    </dd>
</dl>

<p>Supplier : </p>
<ol>
    @foreach (var item in supplierproduct)
    {
        <li>@Html.DisplayFor(mod => item.SupplierId)</li>
    }
</ol>


@using (Html.BeginForm("StockCardDetails", "Manager", FormMethod.Post))
{
    <p>Creation Date Range:</p>
    <p>From: <input type="date" name="startDate" required /> To: <input type="date" name="endDate" required /></p>
    <br />
    <input type="submit" value="Search By Date" />
    <br />
    <br />
}


<table class="table">
    <tr>
        <th>
            Date
        </th>
        <th>
            Qty
        </th>
        <th>
            Total Balance
        </th>
        <th>
            Remarks
        </th>
    </tr>

    @foreach (var item in stockcarddetails)
    {
        <tr>
            <td>
                @Html.DisplayFor(mod => item.TranDate)
            </td>
            <td>
                @Html.DisplayFor(mod => item.Qty)
            </td>
            <td>
                @Html.DisplayFor(mod => item.TotalBalance)
            </td>
            <td>
                @Html.DisplayFor(mod => item.Remarks)
            </td>
        </tr>
    }

</table>


<div>
    @Html.ActionLink("Back to List", "ProductDetails", new { category = Model.Category })
</div>

logicProject/logicProject/Views/Manager/ViewVoucherList.cshtml
@using logicProject.Models.EF;
@using logicProject.Models.DBContext; @*importing the database to retrieve the user name*@
@model logicProject.Models.EF.Adjustment

@{
    ViewBag.Title = "ViewVoucherList";

    List<Adjustment> cart_list = (List<Adjustment>)ViewData["cart_list"];
    StoreStaff user = (StoreStaff)Session["user"];
    Layout = "~/Views/Manager/_ManagerLayout.cshtml";
    //Written By Udaya
    LogicEntities db = new LogicEntities();
}

<h2>Store Manager Voucher List</h2>
<br />

<table border="1">
    <thead>
        <tr>
            <td><strong>Voucher No</strong></td>
            <td><strong>Store Clerk</strong></td>
            <td><strong>Date Created</strong></td>
            <td><strong>Status</strong></td>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in cart_list)
        {

            <tr>
                <td>
                    <button onclick='location.href="@Url.Action("ApproveForm","Manager", new RouteValueDictionary ( new { id = @item.AdjustmentId } ))"' name="button">@item.AdjustmentId</button>
                </td>
                <td>
                    @db.StoreStaff.Where(e => e.StaffId == item.StaffId).Select(e => e.StaffName).First()
                    @*@item.StaffId*@
                </td>
                <td>
                    @Convert.ToDateTime(@item.AdjustedDate).Date.ToString("dd/MM/yyyy")

                </td>
                <td>
                    @item.Status
                </td>
            </tr>

        }

    </tbody>
</table>

<style>
    table {
        border: 1px solid black;
        width: 100%;
    }

    tr, td {
        padding: 10px;
        border: 1px solid black;
        text-align: center;
    }
</style>