logicProject/logicProject/Models/ViewModel/ItemSuppliedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using logicProject.Models.EF;

namespace logicProject.Models.ViewModel
{
    //Coded by Antonio
    public class ItemSuppliedViewModel
    {
        public Product product { get; set; }
        public Supplier supplier { get; set; }
        public SupplierProduct supplierproduct { get; set; }
    }
}

logicProject/logicProject/Controllers/SupervisorController.cs
using logicProject.Models.DAO;
using logicProject.Models.DBContext;
using logicProject.Models.EF;
using logicProject.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using logicProject.Utility;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace logicProject.Controllers
{
    public class SupervisorController : Controller
    {
        LogicEntities db = new LogicEntities();
        private PurchaseOrderDAO purchaseOrderDAO = new PurchaseOrderDAO();
        private StoreStaffDAO storestaffDAO = new StoreStaffDAO();
        // GET: Supervisor
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductCategory()
        {
            var categories = db.Product.Select(p => p.Category).Distinct().ToList();
            ViewData["category"] = categories;
            return View();
        }

        public ActionResult ProductDetails(string category)
        {
            List<Product> products = db.Product.Where(pro => pro.Category == category).ToList();
            ViewData["productdetails"] = products;
            ViewData["category"] = category;
            return View();
        }

        public ActionResult StockCardDetails(string id, string startDate, string endDate)
        {
            Product product = db.Product.Find(id);

            List<SupplierProduct> supplierproduct = db.SupplierProduct.OrderBy(pro => pro.Price).Where(pro => pro.ProductId == id).ToList();
            ViewData["supplierproduct"] = supplierproduct;

            if (startDate != null && endDate != null)
            {
                DateTime start = DateTime.Parse(startDate);
                DateTime end = DateTime.Parse(endDate);
                List<StockTransaction> stockCardDetails = db.StockTransaction.Where(p => p.ProductId == id && p.TranDate > start && p.TranDate < end).ToList();
                ViewData["stockcarddetails"] = stockCardDetails;
            }
            else
            {
                List<StockTransaction> stockCardDetails = db.StockTransaction.Where(p => p.ProductId == id).ToList();
                ViewData["stockcarddetails"] = stockCardDetails;
            }

            return View(product);
        }

        public ActionResult SupplierList()
        {
            return View(db.Supplier.ToList());
        }

        public ActionResult ItemSupplied(string supplierid)
        {
            //SELECT s.ProductId,p.Category,p.[Description],s.Price
            //FROM SupplierProducts s, Suppliers sp,Products p
            //WHERE s.SupplierId = 'ALPA' AND p.ProductId = s.ProductId AND s.SupplierId = sp.SupplierId;

            SupplierProduct suppro = db.SupplierProduct.Where(pro => pro.SupplierId == supplierid).First();

            List<Product> products = db.Product.ToList();
            List<Supplier> suppliers = db.Supplier.ToList();
            List<SupplierProduct> supplierproducts = db.SupplierProduct.Where(sup => sup.SupplierId == supplierid).ToList();

            if (suppro == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewData["supplierproducts"] = suppro;
            }

            List<ItemSuppliedViewModel> data = (from sp in supplierproducts
                                                join s in suppliers on sp.SupplierId equals s.SupplierId
                                                join p in products on sp.ProductId equals p.ProductId
                                                select new ItemSuppliedViewModel { product = p, supplier = s, supplierproduct = sp }).ToList();

            return View(data);
        }
        public ActionResult DepartmentDetails()
        {

            List<ViewModelDepartment> dep = db.Department
                .Select(x => new ViewModelDepartment { collectionpoint = x.CollectionPoint, department = x, headname = db.DepartmentStaff.Where(y => y.DeptId == x.DeptId && x.HeadId == y.StaffId).Select(y => y.StaffName).FirstOrDefault(), Repname = db.DepartmentStaff.Where(y => y.DeptId == x.DeptId && x.RepId == y.StaffId).Select(y => y.StaffName).FirstOrDefault() }).ToList();

            return View(dep);
        }

        //public ActionResult EditDepartmentDetails(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Department department = db.Department.Find(id);
        //    if (department == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.CollectionPt = new SelectList(db.CollectionPoint, "CollectionPtId", "CollectionPt", department.CollectionPt);

        //    return View(department);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditDepartmentDetails([Bind(Include = "DeptId,DeptName,ContactName,PhNo,FaxNo,EmailAddr,HeadId,CollectionPt,RepId")] Department department)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(department).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("DepartmentDetails");
        //    }
        //    ViewBag.CollectionPt = new SelectList(db.CollectionPoint, "CollectionPtId", "CollectionPt", department.CollectionPt);
        //    return View(department);
        //}
        //Code from Antonio ends here
        //Code from Zhen Xiang begins below
        public ActionResult FindPO(string startDate, string endDate, string status)
        {
            List<PurchaseOrder> purchaseOrders = new List<PurchaseOrder>();
            List<StoreStaff> creators = new List<StoreStaff>();

            //if (PONumber != null)
            //{
            //    int number = Convert.ToInt32(PONumber);
            //    purchaseOrders = purchaseOrderDAO.GetPurchaseOrders(number);
            //}
            if (startDate != null && endDate != null)
            {
                DateTime start = DateTime.Parse(startDate);
                DateTime end = DateTime.Parse(endDate);
                purchaseOrders = purchaseOrderDAO.GetPurchaseOrders(start, end);
            }
            else if (status != "")
            {
                purchaseOrders = purchaseOrderDAO.GetPurchaseOrders(status);
            }

            if (purchaseOrders.Count != 0)
            {
                foreach (PurchaseOrder po in purchaseOrders)
                {
                    StoreStaff storeStaff = storestaffDAO.GetStoreStaffbyPONumber(po.StaffId);
                    creators.Add(storeStaff);
                }
            }

            ViewData["creators"] = creators;
            ViewData["purchaseOrders"] = purchaseOrders;

            return View();
        }

        public ActionResult DetailedPO(int id)
        {
            PurchaseOrder po = new PurchaseOrder();
            StoreStaff creator = new StoreStaff();
            Supplier supplier = new Supplier();
            List<PurchaseOrderDetail> poDetails = new List<PurchaseOrderDetail>();
            List<Product> poProducts = new List<Product>();
            List<SupplierProduct> priceList = new List<SupplierProduct>();
            //method cannot be put in a seperate class (DAO), otherwise the other fields cannot be populated
            using (db = new LogicEntities())
            {
                var result = from o in db.PurchaseOrder
                             where o.OrderId == id
                             select o;
                po = result.First();
                var result2 = from ss in db.StoreStaff
                              where ss.StaffId == po.StaffId
                              select ss;
                creator = result2.First();
                supplier = po.Supplier;
                priceList = po.Supplier.SupplierProduct.ToList();
                poDetails = po.RequestDetails.ToList();

                foreach (PurchaseOrderDetail pod in poDetails)
                {
                    poProducts.Add(pod.Product);
                }
            }

            ViewData["PO"] = po;
            ViewData["creator"] = creator;
            ViewData["supplier"] = supplier;
            ViewData["poDetails"] = poDetails;
            ViewData["priceList"] = priceList;

            return View();
        }

        public ActionResult ApprovePO(string status, string remarks, int id)
        {
            purchaseOrderDAO.SetPOStatus(status, remarks, id);
            PurchaseOrder purchaseOrder = purchaseOrderDAO.GetPurchaseOrder(id);
            StoreStaff storeStaff = storestaffDAO.GetStaffbyId(purchaseOrder.StaffId);
            List<string> emails = new List<string>();
            emails.Add(storeStaff.StaffEmail);
            string subj = "Status of PO: " + purchaseOrder.OrderId.ToString();
            string msg = "Dear " + storeStaff.StaffName + ",\n Your PO: " + purchaseOrder.OrderId.ToString() + " has been " + purchaseOrder.Status + ".";
            EmailService.SendEmail(emails, subj, msg);
            return RedirectToAction("FindPO");
        }
        //Code Written By Zhen Xiang ends here
        //Code Below Written By Udaya
        public ActionResult ApproveForm(int id)
        {

            List<AdjustmentDetail> cart_list;

            using (LogicEntities db = new LogicEntities())
            {
                cart_list = db.AdjustmentDetail.Where(item => item.AdjustmentId == id).ToList();
                Adjustment req = db.Adjustment.Where(x => x.AdjustmentId == id).SingleOrDefault();

                ViewData["cart_list"] = cart_list;
                ViewData["adjustment"] = req;
                db.SaveChanges();
            }



            return View();
        }

        [HttpPost]

logicProject/logicProject/Views/Supervisor/ApproveForm.cshtml
@using logicProject.Models.EF;
@model logicProject.Models.EF.AdjustmentDetail


@{
    ViewBag.Title = "ApproveForm";
    Layout = "~/Views/Supervisor/_SupervisorLayout.cshtml";
    //Written By Udaya

    List<AdjustmentDetail> cart_list = (List<AdjustmentDetail>)ViewData["cart_list"];
    StoreStaff user = (StoreStaff)Session["user"];
    Adjustment reqId = ViewData["adjustment"] as Adjustment;
}

<h2>Approve Inventory Adjustment Status</h2>

@using (Html.BeginForm("ApproveForm", "Supervisor", FormMethod.Post))
{
    <div class="box">
        <div id="table1">

            <table style="border: 1px solid black">
                <thead>
                    <tr>
                        <td>
                            <strong>Product code</strong>
                        </td>
                        <td>
                            <strong>Qty</strong>
                        </td>
                        <td>
                            <strong>Unit price</strong>
                        </td>
                        <td>
                            <strong>Total price</strong>
                        </td>
                        <td>
                            <strong>Reason</strong>
                        </td>
                    </tr>
                </thead>


                @foreach (var item in cart_list)
                {
                    <tr>
                        <td>
                            @item.ProductId
                        </td>
                        <td>
                            @item.Qty
                        </td>
                        <td>
                            @item.UnitPrice
                        </td>
                        <td>
                            @item.TotalPrice
                        </td>
                        <td>
                            @item.reason
                        </td>
                    </tr>
                }


            </table>
        </div>

        <br />
        <br />

        @{ if (reqId.Status.Equals("Pending"))
            {
                <input type="hidden" name="id" value="@reqId.AdjustmentId" />
                <p><strong>Remarks:</strong>@Html.TextArea("remarks", null, new { @class = "form-control", rows = "4", cols = "50" })</p>
                <br />
                <input type="submit" name="approve" value="Approve" class="btn btn btn-bitbucket" />
                <input type="submit" name="reject" value="Reject" class="btn btn-pinterest" />
            }

        }

    </div>

    <style>
        table {
            border: 1px solid black;
            width: 100%;
        }

        tr, td {
            padding: 10px;
            border: 1px solid black;
            text-align: center;
        }
    </style>
}

logicProject/logicProject/Views/Supervisor/Chart.cshtml
@{
    /**/

    var list1 = ViewBag.MONS;
    var list2 = ViewBag.QTYS;
    Dictionary<string, string> dict_ = ViewBag.dict;
    string month = (string)ViewBag.monthid;
    string itemselectedid = (string)ViewBag.itemid;
    ViewBag.Title = "Chart";
    Layout = "~/Views/Supervisor/_SupervisorLayout.cshtml";
    //Written by Udaya
    Dictionary<string, string> dict = new Dictionary<string, string>() { { "Select Category", "0" }, { "Clip", "1" }, { "Envelope", "2" }, { "Eraser", "3" }, { "Exercise", "4" }, { "File", "5" }, { "Pen", "6" }, { "Puncher", "7" },
       { "Pad", "8" }, { "Paper", "9" }, { "Ruler", "10" }, { "Scissors", "11" }, { "Tape", "12" }, { "Sharpener", "13" }, { "ShortHand", "14" }, { "Stapler", "15" }, { "Tacks", "16" }, { "Tparency", "17" }, { "tray", "18" }};
    Dictionary<string, string> mon = new Dictionary<string, string>() { { "Select Month", "0" }, { "jan", "1" }, { "feb", "2" }, { "mar", "3" }, { "apr", "4" }, { "may", "5" }, { "jun", "6" }, { "jul", "7" }, { "aug", "8" }, { "sep", "9" }, { "oct", "10" }, { "nov", "11" }, { "dec", "12" } };
    string monthselected = mon.Where(x => x.Value == month).Select(x => x.Key).First() == null ? "mar" : mon.Where(x => x.Value == month).Select(x => x.Key).First();
    string itemselected = dict.Where(x => x.Value == itemselectedid).Select(x => x.Key).First() == null ? "Clip" : dict.Where(x => x.Value == itemselectedid).Select(x => x.Key).First();
}
<head>
    <script src="~/Scripts/Chart.min.js"></script>


    <style>
        #chart_container {
            width: 400px;
            height: 400px;
            border: 1px solid #ddd;
            padding: 1px;
            border-radius: 4px;
            float: left;
            clear: left;
        }

        #report {
            float: left;
            clear: right;
            padding-left: 30px;
        }
    </style>
</head>
<script>
    function onChange() {
        var e = document.getElementById("itemId");
        console.log(e.options[e.selectedIndex].value);
        var etochange = document.getElementById("ITEMID");
        etochange.value = e.options[e.selectedIndex].value;
    };
    function onChange_() {
        var e = document.getElementById("monId");
        console.log(e.options[e.selectedIndex].value);

        var etochange = document.getElementById("MONID");
        etochange.value = e.options[e.selectedIndex].value;

    };
</script>

<h2>Stationery Trend Analysis and Prediction</h2>

@using (Html.BeginForm("GenChart", "Supervisor", FormMethod.Post))
{

    <div id="generate_chart">
        <table>

            <tr>

                <td>
                    <strong>Item:    </strong>
                    @Html.DropDownList("Select Item", dict.Select(item => new SelectListItem { Text = item.Key, Value = item.Value }), new { id = "itemId", onchange = "onChange()", required = true })
                </td>

                <td>
                    <strong>Month:    </strong>
                    @Html.DropDownList("Select Item", mon.Select(item => new SelectListItem { Text = item.Key, Value = item.Value }), new { id = "monId", onchange = "onChange_()", required = true })

                </td>

                <td>
                    <input type="hidden" value="1" name="ITEMID" id="ITEMID" />
                    <input type="hidden" value="1" name="MONID" id="MONID" />
                    <input type="submit" value="Generate chart" />
                </td>
            </tr>

        </table>

    </div>

}
<div id="chart_container">
    <canvas id="bar_chart"></canvas>

</div>

<br />


@if (ViewBag.status)
{
    <div id="report">
        <div>
            <strong>Predicted Category :</strong> @itemselected
        </div>
        <div>
            <strong>Predicted month :</strong> @monthselected
        </div>
        <div>
            <strong>Projected demand for @monthselected : </strong>@dict_[@monthselected]
        </div>
    </div>

}


<script>

        var monthArray = @Html.Raw(Json.Encode(@dict_.Keys));
        var qtys = @Html.Raw(Json.Encode(dict_.Values));


        var ctx = $("#bar_chart");
        var barChart = new Chart(ctx, {

            type: 'bar',
            data: {
                labels: monthArray,
                datasets: [{
                    label: "Stationery Bar Chart",
                    data: qtys,
                    backgroundColor: ["rgba(242,166,54,.5)", "rgba(145,65,72,.5)", "rgba(74,25,92,.5)"],
                    borderColor: ["rgb(242,166,54)", "rgb(145,65,72)", "rgb(74,25,92)"],
                    borderWidth: 1

                }]
            },

            options: {

                maintainAspectRatio: false,
                scales: { xAxes: [{ ticks: { beginAtZero: true } }], yAxes: [{ ticks: { beginAtZero: true }}] },
                legend: {display:false}
            },

        });

</script>



<style>

    table {
        border-collapse: collapse;
    }

    .gfg {
        border-collapse: separate;
        border-spacing: 0 15px;
    }

    th, td {
        width: 220px;
        text-align: center;
        padding: 5px
    }

    #generate_chart {
        padding-bottom: 25px;
    }
</style>

logicProject/logicProject/Views/Supervisor/DepartmentDetails.cshtml
@model IEnumerable<logicProject.Models.ViewModel.ViewModelDepartment>

@{
    ViewBag.Title = "DepartmentDetails";
    Layout = "~/Views/Supervisor/_SupervisorLayout.cshtml";
    //Coded by Antonio
}

<h2>Department Details</h2>

<table class="table">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.department.DeptId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department.DeptName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department.ContactName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department.PhNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department.FaxNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department.EmailAddr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.collectionpoint.CollectionPt)
        </th>
        <th>
            Head Name
        </th>
        <th>
            Rep Name
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.department.DeptId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department.DeptName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department.ContactName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department.PhNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department.FaxNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department.EmailAddr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.collectionpoint.CollectionPt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.headname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Repname)
            </td>
            <td>

            </td>
        </tr>
    }

</table>

logicProject/logicProject/Views/Supervisor/DetailedPO.cshtml
@using logicProject.Models.EF;

@{
    ViewBag.Title = "DetailedPO";
    PurchaseOrder po = (PurchaseOrder)ViewData["PO"];
    StoreStaff creator = (StoreStaff)ViewData["creator"];
    Supplier supplier = (Supplier)ViewData["supplier"];
    List<PurchaseOrderDetail> poDetails = (List<PurchaseOrderDetail>)ViewData["poDetails"];
    List<SupplierProduct> priceList = (List<SupplierProduct>)ViewData["priceList"];
    Layout = "~/Views/Supervisor/_SupervisorLayout.cshtml";
    double subtotal = 0;
    //Written by Zhen Xiang
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

@section Styles {

    <link rel="stylesheet" href="https://max.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
}

<h2>PO number: @po.OrderId</h2>

<p>Supplier: @supplier.SupplierName</p>

<p>Created by: @creator.StaffName</p>

<p>Created on: @po.OrderDate</p>

@if (po.Status == "Approved")
{
    <p>Approved Date: @po.ApprovedDate</p>
}

<table id="detailTable" class="table table-striped table-bordered table-sm table-responsive table-hover cell-border">
    <tr>
        <th>Item Code</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit of Measure</th>
        <th>Unit Price</th>
        <th>Total</th>
    </tr>
    @foreach (PurchaseOrderDetail pod in poDetails)
    {

        <tr>
            <td>@pod.ProductId</td>
            <td>@pod.Product.Description</td>
            <td>@pod.ReqQty</td>
            <td>@pod.Product.Unit</td>
            <td>@priceList.Find(x => x.ProductId == pod.ProductId).Price</td>
            <td>@(priceList.Find(x => x.ProductId == pod.ProductId).Price * pod.ReqQty)</td>
        </tr>
        subtotal = subtotal + priceList.Find(x => x.ProductId == pod.ProductId).Price * pod.ReqQty;
    }
    <tr>
        <td colspan="5" align="right">Subtotal: </td>
        <td>@subtotal</td>
    </tr>
</table>

@if (po.Status == "Pending")
{
    using (Html.BeginForm("ApprovePO", "Supervisor", FormMethod.Post, new { id = "commentForm" }))
    {
        <br />
        <input type="hidden" name="id" value="@po.OrderId" />
        <p>Remarks:</p>
        <textarea id="remarks" name="remarks" form="commentForm" rows="2" cols="30" required></textarea>
        <br />
        <span>
            Approve: <input type="radio" id="Approved" name="status" value="Approved" />
            Reject: <input type="radio" id="Rejected" name="status" value="Rejected" checked />
        </span>
        <input type="submit" value="Submit" />
    }
}

<script>
    $("#Rejected").change(function () {
        if ($("#Rejected:checked", true)) {
            $("#remarks").prop("required", true);
        }
    });
    $("#Approved").change(function () {
        if ($("#Approved:checked", true)) {
            $("#remarks").prop("required", false);
        }
    });
</script>

@section Scripts {

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#detailTable').DataTable();
        })
    </script>
}

logicProject/logicProject/Views/Supervisor/FindPO.cshtml
@using logicProject.Models.EF;

@{
    ViewBag.Title = "FindPO";
    List<PurchaseOrder> purchaseOrders = (List<PurchaseOrder>)ViewData["purchaseOrders"];
    List<StoreStaff> creators = (List<StoreStaff>)ViewData["creators"];
    Layout = "~/Views/Supervisor/_SupervisorLayout.cshtml";
    //Written by Zhen Xiang
}

@section Styles {

    <link rel="stylesheet" href="https://max.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
}

<h2>Find Purchase Order</h2>

<p>Welcome to the PO page. Please search for the PO using the options provided</p>

@using (Html.BeginForm("FindPO", "Supervisor", FormMethod.Post))
{
    <select name="status">
        <option value=""></option>
        <option value="Pending">Pending</option>
        <option value="Approved">Approved</option>
        <option value="Rejected">Rejected</option>
    </select>
    <br />
    <input type="submit" value="Search By Status" />
    <br />
}

@using (Html.BeginForm("FindPO", "Supervisor", FormMethod.Post))
{
    <p>Creation Date Range:</p>
    <p>From: <input type="date" name="startDate"> To: <input type="date" name="endDate" /></p>
    <br />
    <input type="submit" value="Search By Date" />
    <br />
}

@*@using (Html.BeginForm("FindPO", "Supervisor", FormMethod.Post))
    {
        <p>PO Number: <input type="text" name="PONumber" /></p>
        <br />
        <input type="submit" value="Search by PO number" />
        <br />
    }*@

@if (purchaseOrders.Count != 0)
{
    <table id="POTable" class="table table-striped table-bordered table-sm table-responsive table-hover cell-border">
        <tr>
            <th>PO Number</th>
            <th>Creating Officer</th>
            <th>Creation Date</th>
            <th>Status</th>
        </tr>
        @foreach (PurchaseOrder po in purchaseOrders)
        {
            <tr>
                <td>@Html.ActionLink(po.OrderId.ToString(), "DetailedPO", "Supervisor", new { id = po.OrderId }, null)</td>
                <td>@creators.Find(x => x.StaffId == po.StaffId).StaffName</td>
                <td>@po.OrderDate.Date.ToString("d")</td>
                <td>@po.Status</td>
            </tr>
        }
    </table>
}

@section Scripts {

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#POTable').DataTable();
        })
    </script>
}

logicProject/logicProject/Views/Supervisor/StockCardDetails.cshtml
@model logicProject.Models.EF.Product
@using logicProject.Models.EF

@{
    ViewBag.Title = "StockCardDetails";
    var supplierproduct = (List<SupplierProduct>)ViewData["supplierproduct"];
    var stockcarddetails = (List<StockTransaction>)ViewData["stockcarddetails"];
    Layout = "~/Views/Supervisor/_SupervisorLayout.cshtml";
    //Written By Antonio
}

<h2>Stock Card Details</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.ProductId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ProductId)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Bin)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Bin)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Unit)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Unit)
    </dd>
</dl>

<p>Supplier : </p>
<ol>
    @foreach (var item in supplierproduct)
    {
        <li>@Html.DisplayFor(mod => item.SupplierId)</li>
    }
</ol>


@using (Html.BeginForm("StockCardDetails", "Supervisor", FormMethod.Post))
{
    <p>Creation Date Range:</p>
    <p>From: <input type="date" name="startDate" required /> To: <input type="date" name="endDate" required /></p>
    <br />
    <input type="submit" value="Search By Date" />
    <br />
    <br />
}


<table class="table">
    <tr>
        <th>
            Date
        </th>
        <th>
            Qty
        </th>
        <th>
            Total Balance
        </th>
        <th>
            Remarks
        </th>
    </tr>

    @foreach (var item in stockcarddetails)
    {
        <tr>
            <td>
                @Html.DisplayFor(mod => item.TranDate)
            </td>
            <td>
                @Html.DisplayFor(mod => item.Qty)
            </td>
            <td>
                @Html.DisplayFor(mod => item.TotalBalance)
            </td>
            <td>
                @Html.DisplayFor(mod => item.Remarks)
            </td>
        </tr>
    }

</table>


<div>
    @Html.ActionLink("Back to List", "ProductDetails", new { category = Model.Category })
</div>